// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_sKniDcrVI3w7OKVQQugXEwRyBezFMAo',
    appId: '1:660835097321:web:6f5468e3b8c72bcde3ee78',
    messagingSenderId: '660835097321',
    projectId: 'educationapp-4780a',
    authDomain: 'educationapp-4780a.firebaseapp.com',
    storageBucket: 'educationapp-4780a.firebasestorage.app',
    measurementId: 'G-3ZSV0NK26V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFgs56T8TAQ8InwukxgP0UCv8Iv2jaks0',
    appId: '1:660835097321:android:4d988b7ee3487315e3ee78',
    messagingSenderId: '660835097321',
    projectId: 'educationapp-4780a',
    storageBucket: 'educationapp-4780a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Oun2OeTZIGJ4MUbciahwUSuIz1h0FdA',
    appId: '1:660835097321:ios:701f120246e45198e3ee78',
    messagingSenderId: '660835097321',
    projectId: 'educationapp-4780a',
    storageBucket: 'educationapp-4780a.firebasestorage.app',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Oun2OeTZIGJ4MUbciahwUSuIz1h0FdA',
    appId: '1:660835097321:ios:701f120246e45198e3ee78',
    messagingSenderId: '660835097321',
    projectId: 'educationapp-4780a',
    storageBucket: 'educationapp-4780a.firebasestorage.app',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_sKniDcrVI3w7OKVQQugXEwRyBezFMAo',
    appId: '1:660835097321:web:029b18f8fb84d80ee3ee78',
    messagingSenderId: '660835097321',
    projectId: 'educationapp-4780a',
    authDomain: 'educationapp-4780a.firebaseapp.com',
    storageBucket: 'educationapp-4780a.firebasestorage.app',
    measurementId: 'G-Z1JCYLHCMW',
  );

}