// lib/main.dart

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
// Import the generated localizations file
//import 'package:education_app/l10n/app_localizations.dart';

// Firebase Core (ensure this is initialized)
import 'package:firebase_core/firebase_core.dart';
import 'package:sud_qollanma/l10n/app_localizations.dart';
import 'package:sud_qollanma/services/community_service.dart';
import 'package:sud_qollanma/services/news_service.dart';
import 'package:sud_qollanma/services/profile_service.dart';
import 'package:sud_qollanma/services/quiz_service.dart';
import 'package:sud_qollanma/services/resource_service.dart';
import 'package:sud_qollanma/services/knowledge_base_service.dart'; // Add this import
// Import your firebase_options.dart (generated by `flutterfire configure`)
import 'firebase_options.dart'; // THIS IMPORT IS CRUCIAL

import 'screens/splash_screen.dart'; // Your splash screen
import 'models/theme_notifier.dart';
import 'models/locale_notifier.dart';
import 'models/auth_notifier.dart'; // Import AuthNotifier
import 'services/auth_service.dart'; // Import AuthService

void main() async {
  // Ensure Flutter bindings are initialized before Firebase
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  // It's crucial to await Firebase.initializeApp() before running the app.
  // This line uses the DefaultFirebaseOptions generated by `flutterfire configure`
  // which should contain platform-specific configurations, including for web.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (context) => ThemeNotifier()),
        ChangeNotifierProvider(create: (context) => LocaleNotifier()),
        // --- MODIFIED: Services that depend on each other ---
        // ProfileService is independent
        Provider<ProfileService>(create: (_) => ProfileService()),
        // AuthService now depends on ProfileService, so we inject it.
        Provider<AuthService>(
          create: (context) => AuthService(context.read<ProfileService>()),
        ),
        // AuthNotifier depends on AuthService and ProfileService
        ChangeNotifierProvider<AuthNotifier>(
          create:
              (context) => AuthNotifier(
                context.read<AuthService>(),
                context.read<ProfileService>(),
              ),
        ),
        Provider<ResourceService>(create: (_) => ResourceService()),

        // Add this line
        Provider<CommunityService>(create: (_) => CommunityService()),
        Provider<QuizService>(create: (_) => QuizService()),
        Provider<NewsService>(create: (_) => NewsService()),
        Provider<KnowledgeBaseService>(create: (_) => KnowledgeBaseService()), // Add this line
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final themeNotifier = context.watch<ThemeNotifier>();
    final localeNotifier = context.watch<LocaleNotifier>();

    // Theme data (assuming your M3 theme setup is here or imported)
    final ColorScheme lightColorScheme = ColorScheme.fromSeed(
      seedColor: Colors.indigo, // O'ZGARISH: Rasmiyroq rang uchun Colors.indigo
      brightness: Brightness.light,
    );
    final ColorScheme darkColorScheme = ColorScheme.fromSeed(
      seedColor: Colors.indigo, // O'ZGARISH: Rasmiyroq rang uchun Colors.indigo
      brightness: Brightness.dark,
    );

    return MaterialApp(
      onGenerateTitle: (BuildContext context) {
        // O'ZGARISH: Nomni lokalizatsiyadan olish
        return AppLocalizations.of(context)?.appTitle ?? 'Sud Qo\'llanmasi';
      },
      themeMode: themeNotifier.themeMode,
      theme: ThemeData(
        colorScheme: lightColorScheme,
        useMaterial3: true,
        scaffoldBackgroundColor: lightColorScheme.surface,
        appBarTheme: AppBarTheme(
          backgroundColor: lightColorScheme.primary,
          foregroundColor: lightColorScheme.onPrimary,
          elevation: 2.0,
        ),
        bottomNavigationBarTheme: BottomNavigationBarThemeData(
          backgroundColor: lightColorScheme.surface,
          selectedItemColor: lightColorScheme.primary,
          unselectedItemColor: lightColorScheme.onSurface.withOpacity(0.7),
          selectedLabelStyle: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 12,
          ),
          unselectedLabelStyle: const TextStyle(fontSize: 12),
          type: BottomNavigationBarType.fixed,
          elevation: 5.0,
        ),
        cardTheme: CardThemeData(
          elevation: 1.0,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12.0),
          ),
          margin: const EdgeInsets.symmetric(horizontal: 8.0, vertical: 4.0),
        ),
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      darkTheme: ThemeData(
        colorScheme: darkColorScheme,
        useMaterial3: true,
        scaffoldBackgroundColor: darkColorScheme.surface,
        appBarTheme: AppBarTheme(
          backgroundColor: darkColorScheme.surface,
          foregroundColor: darkColorScheme.onSurface,
          elevation: 2.0,
        ),
        bottomNavigationBarTheme: BottomNavigationBarThemeData(
          backgroundColor: darkColorScheme.surface,
          selectedItemColor: darkColorScheme.primary,
          unselectedItemColor: darkColorScheme.onSurface.withOpacity(0.7),
          selectedLabelStyle: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 12,
          ),
          unselectedLabelStyle: const TextStyle(fontSize: 12),
          type: BottomNavigationBarType.fixed,
          elevation: 5.0,
        ),
        cardTheme: CardThemeData(
          elevation: 2.0,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12.0),
          ),
          margin: const EdgeInsets.symmetric(horizontal: 8.0, vertical: 4.0),
        ),
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      locale: localeNotifier.appLocale,
      supportedLocales: const [
        Locale('en', ''),
        Locale('uz', ''),
        Locale('ru', ''),
      ],
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      home: const SplashScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}
