// lib/main.dart

import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart'; // For kIsWeb
import 'dart:ui'; // For PlatformDispatcher
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:provider/provider.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
// Import the generated localizations file
//import 'package:education_app/l10n/app_localizations.dart';

// Firebase Core (ensure this is initialized)
import 'package:firebase_core/firebase_core.dart';
import 'package:sud_qollanma/l10n/app_localizations.dart';
import 'package:sud_qollanma/services/community_service.dart';
import 'package:sud_qollanma/services/news_service.dart';
import 'package:sud_qollanma/services/profile_service.dart';
import 'package:sud_qollanma/services/quiz_service.dart';
import 'package:sud_qollanma/services/resource_service.dart';
import 'package:sud_qollanma/services/knowledge_base_service.dart';
import 'package:sud_qollanma/services/video_tutorial_service.dart';
import 'package:sud_qollanma/services/systems_service.dart';
import 'package:sud_qollanma/services/faq_service.dart';
import 'package:sud_qollanma/services/notification_service.dart';

// Screens
import 'package:sud_qollanma/screens/knowledge_base/knowledge_base_screen.dart';
import 'package:sud_qollanma/screens/resource/video_tutorials_screen.dart';
import 'package:sud_qollanma/screens/systems/systems_directory_screen.dart';
import 'package:sud_qollanma/screens/faq/faq_list_screen.dart';

// Import your firebase_options.dart (generated by `flutterfire configure`)
import 'firebase_options.dart'; // THIS IMPORT IS CRUCIAL

import 'screens/splash_screen.dart'; // Your splash screen
import 'models/theme_notifier.dart';
import 'models/locale_notifier.dart';
import 'models/auth_notifier.dart'; // Import AuthNotifier
import 'services/auth_service.dart'; // Import AuthService

void main() async {
  // Ensure Flutter bindings are initialized before Firebase
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  // It's crucial to await Firebase.initializeApp() before running the app.
  // This line uses the DefaultFirebaseOptions generated by `flutterfire configure`
  // which should contain platform-specific configurations, including for web.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  
  // Pass all uncaught "fatal" errors from the framework to Crashlytics
  if (!kIsWeb) {
    FlutterError.onError = (errorDetails) {
      FirebaseCrashlytics.instance.recordFlutterFatalError(errorDetails);
    };
    // Pass all uncaught asynchronous errors that aren't handled by the Flutter framework to Crashlytics
    PlatformDispatcher.instance.onError = (error, stack) {
      FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
      return true;
    };
  }

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (context) => ThemeNotifier()),
        ChangeNotifierProvider(create: (context) => LocaleNotifier()),
        // --- MODIFIED: Services that depend on each other ---
        // ProfileService is independent
        Provider<ProfileService>(create: (_) => ProfileService()),
        // AuthService now depends on ProfileService, so we inject it.
        Provider<AuthService>(
          create: (context) => AuthService(context.read<ProfileService>()),
        ),
        // AuthNotifier depends on AuthService and ProfileService
        ChangeNotifierProvider<AuthNotifier>(
          create:
              (context) => AuthNotifier(
                context.read<AuthService>(),
                context.read<ProfileService>(),
              ),
        ),
        ChangeNotifierProvider<ResourceService>(create: (_) => ResourceService()),

        // Add this line
        Provider<CommunityService>(create: (_) => CommunityService()),
        Provider<QuizService>(create: (_) => QuizService()),
        Provider<NewsService>(create: (_) => NewsService()),
        Provider<KnowledgeBaseService>(create: (_) => KnowledgeBaseService()),
        Provider<VideoTutorialService>(create: (_) => VideoTutorialService()),
        Provider<SystemsService>(create: (_) => SystemsService()),
        Provider<FAQService>(create: (_) => FAQService()),
        Provider<NotificationService>(create: (_) => NotificationService()),
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final themeNotifier = context.watch<ThemeNotifier>();
    final localeNotifier = context.watch<LocaleNotifier>();

    // Theme data (assuming your M3 theme setup is here or imported)
    final ColorScheme lightColorScheme = ColorScheme.fromSeed(
      seedColor: Colors.indigo, // O'ZGARISH: Rasmiyroq rang uchun Colors.indigo
      brightness: Brightness.light,
    );
    final ColorScheme darkColorScheme = ColorScheme.fromSeed(
      seedColor: Colors.indigo, // O'ZGARISH: Rasmiyroq rang uchun Colors.indigo
      brightness: Brightness.dark,
    );

    return MaterialApp(
      onGenerateTitle: (BuildContext context) {
        // O'ZGARISH: Nomni lokalizatsiyadan olish
        return AppLocalizations.of(context)?.appTitle ?? 'Sud Qo\'llanmasi';
      },
      themeMode: themeNotifier.themeMode,
      theme: ThemeData(
        colorScheme: lightColorScheme,
        useMaterial3: true,
        scaffoldBackgroundColor: lightColorScheme.surface,
        appBarTheme: AppBarTheme(
          backgroundColor: lightColorScheme.primary,
          foregroundColor: lightColorScheme.onPrimary,
          elevation: 2.0,
        ),
        bottomNavigationBarTheme: BottomNavigationBarThemeData(
          backgroundColor: lightColorScheme.surface,
          selectedItemColor: lightColorScheme.primary,
          unselectedItemColor: lightColorScheme.onSurface.withValues(alpha: 0.7),
          selectedLabelStyle: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 12,
          ),
          unselectedLabelStyle: const TextStyle(fontSize: 12),
          type: BottomNavigationBarType.fixed,
          elevation: 5.0,
        ),
        cardTheme: CardThemeData(
          elevation: 1.0,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12.0),
          ),
          margin: const EdgeInsets.symmetric(horizontal: 8.0, vertical: 4.0),
        ),
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      darkTheme: ThemeData(
        colorScheme: darkColorScheme,
        useMaterial3: true,
        scaffoldBackgroundColor: darkColorScheme.surface,
        appBarTheme: AppBarTheme(
          backgroundColor: darkColorScheme.surface,
          foregroundColor: darkColorScheme.onSurface,
          elevation: 2.0,
        ),
        bottomNavigationBarTheme: BottomNavigationBarThemeData(
          backgroundColor: darkColorScheme.surface,
          selectedItemColor: darkColorScheme.primary,
          unselectedItemColor: darkColorScheme.onSurface.withValues(alpha: 0.7),
          selectedLabelStyle: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 12,
          ),
          unselectedLabelStyle: const TextStyle(fontSize: 12),
          type: BottomNavigationBarType.fixed,
          elevation: 5.0,
        ),
        cardTheme: CardThemeData(
          elevation: 2.0,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12.0),
          ),
          margin: const EdgeInsets.symmetric(horizontal: 8.0, vertical: 4.0),
        ),
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      locale: localeNotifier.appLocale,
      supportedLocales: const [
        Locale('en', ''),
        Locale('uz', ''),
        Locale('ru', ''),
      ],
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      home: const SplashScreen(),
      routes: {
        '/knowledge_base': (context) => const KnowledgeBaseScreen(),
        '/video_tutorials': (context) => const VideoTutorialsScreen(),
        '/systems': (context) => const SystemsDirectoryScreen(),
        '/faq': (context) => const FAQListScreen(),
      },
      debugShowCheckedModeBanner: false,
    );
  }
}
