import 'package:flutter/material.dart';
import '../../models/faq.dart';
import '../../services/faq_service.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class AdminAddEditFAQScreen extends StatefulWidget {
  final FAQ? faq;

  const AdminAddEditFAQScreen({super.key, this.faq});

  @override
  State<AdminAddEditFAQScreen> createState() => _AdminAddEditFAQScreenState();
}

class _AdminAddEditFAQScreenState extends State<AdminAddEditFAQScreen> {
  final _formKey = GlobalKey<FormState>();
  final _service = FAQService();
  
  late TextEditingController _questionController;
  late TextEditingController _answerController;
  FAQCategory _selectedCategory = FAQCategory.general;
  
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    _questionController = TextEditingController(text: widget.faq?.question ?? '');
    _answerController = TextEditingController(text: widget.faq?.answer ?? '');
    _selectedCategory = widget.faq?.category ?? FAQCategory.general;
  }

  @override
  void dispose() {
    _questionController.dispose();
    _answerController.dispose();
    super.dispose();
  }

  Future<void> _saveFAQ() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      if (widget.faq == null) {
        // Create new
        final newFAQ = FAQ(
          id: '', // ID will be generated by Firestore
          question: _questionController.text,
          answer: _answerController.text,
          category: _selectedCategory,
          createdAt: Timestamp.now(),
          updatedAt: Timestamp.now(),
        );
        await _service.createFAQ(newFAQ);
      } else {
        // Update existing
        final updatedFAQ = widget.faq!.copyWith(
          question: _questionController.text,
          answer: _answerController.text,
          category: _selectedCategory,
          updatedAt: Timestamp.now(),
        );
        await _service.updateFAQ(widget.faq!.id, updatedFAQ);
      }

      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Savol saqlandi')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Xatolik: $e')),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.faq == null ? 'Yangi Savol' : 'Savolni Tahrirlash'),
        actions: [
          IconButton(
            icon: const Icon(Icons.save),
            onPressed: _isLoading ? null : _saveFAQ,
          ),
        ],
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    DropdownButtonFormField<FAQCategory>(
                      value: _selectedCategory,
                      decoration: const InputDecoration(
                        labelText: 'Kategoriya',
                        border: OutlineInputBorder(),
                      ),
                      items: FAQCategory.values.map((category) {
                        return DropdownMenuItem(
                          value: category,
                          child: Text('${category.icon} ${category.displayName}'),
                        );
                      }).toList(),
                      onChanged: (value) {
                        if (value != null) {
                          setState(() => _selectedCategory = value);
                        }
                      },
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _questionController,
                      decoration: const InputDecoration(
                        labelText: 'Savol',
                        border: OutlineInputBorder(),
                      ),
                      maxLines: 2,
                      validator: (value) =>
                          value?.isEmpty ?? true ? 'Savol kiritilishi shart' : null,
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _answerController,
                      decoration: const InputDecoration(
                        labelText: 'Javob (Markdown)',
                        border: OutlineInputBorder(),
                        alignLabelWithHint: true,
                      ),
                      maxLines: 10,
                      validator: (value) =>
                          value?.isEmpty ?? true ? 'Javob kiritilishi shart' : null,
                    ),
                  ],
                ),
              ),
            ),
    );
  }
}
